### ISSUE TITLE
Session session is null

### ISSUE THREAD

**Issue by LapinW** [seek-for-android/pool#91]
Hello

This is my problem : 
`Reader[] readers = seService.getReaders();
if (readers.length < 1)
return;

Log.i(LOG_TAG, "Create Session from the first reader...");
Session session = readers[0].openSession();`

the program detects the readers but can't open a session. He returns "Session session is null" and i have no idea why he returns this.

Can you help me please ?

**Comment by krunalindrodiya** [comment]
I have same issue facing in my code. I got null pointer exception at same line.

` java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.mobilesecuritycard.openmobileapi.service.ITerminalService.isCardPresent()' on a null object reference`

Did you solve..?

**Comment by marcobrador** [comment]
Hi guys,

Please use the mailing list (https://groups.google.com/forum/#!forum/seek-for-android) for this kind of support request. Let's keep this issue tracker for actual bugs of the source code.

Best regards,
Marc
