### ISSUE TITLE
SEService return null object.

### ISSUE THREAD

**Issue by krunalindrodiya** [seek-for-android/pool#93]
Hi i am using com.mobilesecuritycard.openmobileapi.jar in my application, and i integrate hello-smartcard-app code in my acitvity. Problem is that when i creating object of SEService at that time getting null object and throw error,

`java.lang.SecurityException: Not allowed to bind to service Intent { act=com.mobilesecuritycard.openmobileapi.BIND_SERVICE pkg=com.mobilesecuritycard.openmobileapi.service }
`
Does anybody have solution for same.

**Comment by marcobrador** [comment]
Hi guys,

Please use the mailing list (https://groups.google.com/forum/#!forum/seek-for-android) for this kind of support request. Let's keep this issue tracker for actual bugs of the source code.

Best regards,
Marc
